### ISSUE TITLE
Failed to build with Make 4.3

### ISSUE THREAD

**Issue by zyoNe-cell** [obfuscator-llvm/obfuscator#180]
**Error**:
/home/ziyang/platforms/llvm-obfuscator/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h:722:26: error: could not convert ‘((llvm::orc::remote::OrcRemoteTargetClient<ChannelT>*)this)->callB<llvm::orc::remote::OrcRemoteTargetRPCAPI::ReadMem>(Src, Size)’ from ‘Expected<vector<unsigned char,allocator<unsigned char>>>’ to ‘Expected<vector<char,allocator<char>>>’
  722 |     return callB<ReadMem>(Src, Size);
      |            ~~~~~~~~~~~~~~^~~~~~~~~~~
      |                          |
      |                          Expected<vector<unsigned char,allocator<unsigned char>>>

_Seems to be an internal bug in the LLVM 4 version._ 
Source:https://bugzilla.redhat.com/show_bug.cgi?id=1540620
