### ISSUE TITLE
error: 'objc_returns_inner_pointer' attribute only applies to methods

### ISSUE THREAD

**Issue by arloan** [obfuscator-llvm/obfuscator#40]
The clang-425.0.24 branch does not compile:

```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:12:1: error: 
      'objc_returns_inner_pointer' attribute only applies to methods
@property (readonly) const char *objCType NS_RETURNS_INNER_POINTER;
^                                         ~~~~~~~~~~~~~~~~~~~~~~~~
```

Environment:
OS X Mavericks
iOS SDK 8.1
Obfuscator compile with XCode 6.1
```
xxxxx$ ./clang++ --version
Obfuscator-LLVM version 3.2  (based on LLVM 3.2svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

**Comment by cryptopathe** [comment]
Please note that the clang-425.0.24 is an old branch that is not supported/compatible anymore by/with recent versions of XCode and various SKDs.
